version: '3'
services:

  # https://hub.docker.com/_/elasticsearch
  # https://www.elastic.co/guide/en/elasticsearch/reference/7.14/docker.html
  elasticsearch:
    container_name: senzing-elasticsearch
    environment:
      - discovery.type=single-node
    image: elasticsearch:7.14.0
    networks:
      - backend
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  # https://hub.docker.com/_/logstash
  # https://www.elastic.co/guide/en/logstash/7.14/docker.html
  logstash:
    command: logstash -f /usr/share/logstash/pipeline/ --config.reload.automatic
    container_name: senzing-logstash
    depends_on:
      - elasticsearch
    environment:
      - "xpack.monitoring.elasticsearch.url=http://senzing-elasticsearch:9200"
    image: logstash:7.14.0
    networks:
      - backend
    ports:
      - 5044:5044
      - 12201:12201/udp
    restart: always
    volumes:
      - ${LOGSTASH_DIR:-.}:/usr/share/logstash/pipeline/

  # https://hub.docker.com/_/kibana
  # https://www.elastic.co/guide/en/kibana/7.14/docker.html
  kibana:
    container_name: senzing-kibana
    depends_on:
      - elasticsearch
      - logstash
    environment:
      ELASTICSEARCH_HOSTS: http://senzing-elasticsearch:9200
    image: kibana:7.14.0
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "senzing-kibana"
    networks:
      - backend
    ports:
      - 5601:5601
    restart: always
#   volumes:
#     - ${KIBANA_DIR:-.}:/usr/share/kibana/config

  rabbitmq:
    container_name: senzing-rabbitmq
    depends_on:
      - kibana
    environment:
#     See https://github.com/bitnami/bitnami-docker-rabbitmq#configuration
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
    image: bitnami/rabbitmq:${SENZING_DOCKER_IMAGE_VERSION_BITNAMI_RABBITMQ:-3.8.19-debian-10-r6}
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "senzing-rabbitmq"
    networks:
      - backend
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    volumes:
      - ${RABBITMQ_DIR}:/bitnami

networks:
  backend:
